/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 road.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d/road.gltf')
  console.log(nodes, materials)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rua_Cubo.geometry} material={nodes.rua_Cubo.material} />
    </group>
  )
}

useGLTF.preload('/3d/road.gltf')
